### ISSUE TITLE
Can you write such a style, so that it is also convenient to use in the obsidian plug-in

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [RochaG07/anki-sync-plus#1]
Can you write such a style, so that it is also convenient to use in the obsidian plug-in, non-programmers suggested
<img width="256" alt="图片" src="https://github.com/RochaG07/anki-obsidian-integration/assets/71814666/34c59f36-7ed2-4426-a373-7b5fa58cbca6">

**Comment by RochaG07** [comment]
I’ve did not released the plugin yet, still need to be reviewed to be placed in Obsidian’s “Community Plugins”

**Comment by shoudeyunkaijianyueming** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        Could you please release a release first? I will install it through beta plug-in and have a taste of it. At the same time, I can find bugs and give you feedback
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1801211637
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        09/8/2023 01:03
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [RochaG07/anki-obsidian-integration] Can you write such a style, so that it is also convenient to use in the obsidian plug-in (Issue #1)
        
      
    
  
  
I’ve did not released the plugin yet, still need to be reviewed to be placed in Obsidian’s “Community Plugins”

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
